version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.part5
    container_name: hello-world
    restart: unless-stopped
    networks:
      - internal
    

  proxy:
    image: nginx:alpine
    container_name: proxy_nginx
    restart: unless-stopped
    ports:
      - "80:8080"
    depends_on:
      - app
      # app:
        # condition: service_healthy
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/nginx.conf
    networks:
      - internal

networks:
  internal:
    driver: bridge
