[k3s_server]
shop-master ansible_host=10.181.19.10

[k3s_agents]
shop-worker1 ansible_host=10.181.19.240
shop-worker2 ansible_host=10.181.19.41

[k3s_cluster:children]
k3s_server
k3s_agents

[k3s_cluster:vars]
ansible_user=ubuntu
ansible_private_key_file=~/.ssh/shop_ansible
ansible_python_interpreter=/usr/bin/python3
